---
server.servlet.context-path: '/${info.app.name}'
---
grails:
    profile: rest-api
    codegen:
        defaultPackage: api3
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    jmx:
        unique-names: true
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    devtools:
        restart:
            additional-exclude:
                - '*.gsp'
                - '**/*.gsp'
                - '*.gson'
                - '**/*.gson'
                - 'logback.groovy'
                - '*.properties'
environments:
    development:
        management:
            endpoints:
                enabled-by-default: true
                web:
                    base-path: '/actuator'
                    exposure:
                        include: '*'
    production:
        management:
            endpoints:
                enabled-by-default: false
server:
    port:
        8180
---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            json:
                - application/json
                - text/json
            hal:
                - application/hal+json
                - application/hal+xml
            xml:
                - text/xml
                - application/xml
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            js: text/javascript
            rss: application/rss+xml
            text: text/plain
            all: '*/*'
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: 'oracle.jdbc.OracleDriver'
    url: 'jdbc:oracle:thin:@insoft-lnx4.insoft.local:1521:desenv01'
    username: 'aluno17'
    password: 'insoft2'
    autocommit: true
#    dbCreate: 'create-drop'

environments:
    development:
        dataSource:
            dbCreate: create-drop
            driverClassName: 'oracle.jdbc.OracleDriver'
            url: 'jdbc:oracle:thin:@insoft-lnx4.insoft.local:1521:desenv01'
            username: 'aluno17'
            password: 'insoft2'
            autocommit: true
    test:
        dataSource:
            dbCreate: update
            driverClassName: 'oracle.jdbc.OracleDriver'
            url: 'jdbc:oracle:thin:@insoft-lnx4.insoft.local:1521:desenv01'
            username: 'aluno17'
            password: 'insoft2'
            autocommit: true
    production:
        dataSource:
            dbCreate: none
            driverClassName: 'oracle.jdbc.OracleDriver'
            url: 'jdbc:oracle:thin:@insoft-lnx4.insoft.local:1521:desenv01'
            username: 'aluno17'
            password: 'insoft2'
            autocommit: true
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED